name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name CosmosCollection --icon=images/CosmosCollection.png main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CosmosCollection-Windows
        path: dist/CosmosCollection.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/CosmosCollection.exe
        draft: false
        prerelease: false
        generate_release_notes: true